kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: radius-sandbox
nodes: 
- role: control-plane
  extraMounts:
  - hostPath: /usr/local/share/ca-certificates/ZscalerRootCA.crt
    containerPath: /usr/local/share/ca-certificates/ZscalerRootCA.crt
    readOnly: true
  - hostPath: /etc/ssl/certs
    containerPath: /etc/ssl/certs
    readOnly: true
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
